import type { Job } from "./types";

export const mockJobs: Job[] = [
  {
    id: 1,
    company: "Vercel",
    title: "مهندس فرانت‌اند ارشد",
    description:
      "در ساخت آینده توسعه وب کمک کنید. به تیم ما برای کار روی Next.js و محاسبات لبه‌ای بپیوندید.",
    location: "San Francisco, CA (دورکاری)",
    city: "San Francisco",
    position: "senior",
    tags: ["React", "TypeScript", "Next.js"],
    posted: "پیش از ۲ روز",
    salary: "$150k - $220k",
    icon: "⚡",
    url: "https://vercel.com/careers",
    type: "remote",
  },
  {
    id: 2,
    company: "Stripe",
    title: "مهندس فرانت‌اند، تجربه پرداختی",
    description:
      "تجربیات پرداخت را طراحی و ایجاد کنید که کسب‌وکارهای جهانی را قدرتمند می‌کند.",
    location: "San Francisco, CA",
    city: "San Francisco",
    position: "midlevel",
    tags: ["React", "Design Systems", "Web"],
    posted: "پیش از ۱ هفته",
    salary: "$160k - $230k",
    icon: "💳",
    url: "https://stripe.com/careers",
    type: "fulltime",
  },
  {
    id: 3,
    company: "Figma",
    title: "مهندس محصول",
    description:
      "معماری فرانت‌اند مقیاس‌پذیر برای پلتفرم طراحی تعاونی جهانی بسازید.",
    location: "دورکاری",
    city: "Remote",
    position: "senior",
    tags: ["WebAssembly", "React", "Performance"],
    posted: "پیش از ۳ روز",
    salary: "$170k - $240k",
    icon: "🎨",
    url: "https://figma.com/careers",
    type: "remote",
  },
  {
    id: 4,
    company: "Linear",
    title: "توسعه‌دهنده فرانت‌اند",
    description:
      "به تیم کوچک ما برای ساخت بهترین پلتفرم ردیابی مسائل برای تیم‌های نرم‌افزار بپیوندید.",
    location: "دورکاری",
    city: "Remote",
    position: "junior",
    tags: ["React", "TypeScript", "Startup"],
    posted: "پیش از ۵ روز",
    salary: "$130k - $180k",
    icon: "📊",
    url: "https://linear.app/careers",
    type: "remote",
  },
  {
    id: 5,
    company: "Spotify",
    title: "مهندس فرانت‌اند ارشد",
    description:
      "تجربیات آنند‌بخش برای میلیون‌ها عاشق موسیقی با استفاده از فناوری‌های وب پیشرفته ایجاد کنید.",
    location: "Stockholm, Sweden",
    city: "Stockholm",
    position: "senior",
    tags: ["React", "JavaScript", "Web Performance"],
    posted: "پیش از ۱ هفته",
    salary: "$140k - $200k",
    icon: "🎵",
    url: "https://spotify.com/careers",
    type: "fulltime",
  },
  {
    id: 6,
    company: "OpenAI",
    title: "مهندس فرانت‌اند (ChatGPT)",
    description:
      "رابط کاربری برای هوش مصنوعی بسازید. در شکل‌گیری نحوه تعامل میلیون‌ها نفر با مدل‌های ما کمک کنید.",
    location: "San Francisco, CA",
    city: "San Francisco",
    position: "senior",
    tags: ["React", "TypeScript", "AI/ML"],
    posted: "پیش از ۲ روز",
    salary: "$160k - $250k",
    icon: "🤖",
    url: "https://openai.com/careers",
    type: "fulltime",
  },
  {
    id: 7,
    company: "Airbnb",
    title: "مهندس فرانت‌اند جونیور",
    description:
      "شروع حرفه خود را با ساخت تجربیات برای مسافران و میزبان‌های جهانی کنید.",
    location: "San Francisco, CA",
    city: "San Francisco",
    position: "junior",
    tags: ["React", "CSS", "JavaScript"],
    posted: "پیش از ۳ روز",
    salary: "$100k - $140k",
    icon: "🏠",
    url: "https://airbnb.com/careers",
    type: "fulltime",
  },
  {
    id: 8,
    company: "Netflix",
    title: "توسعه‌دهنده فرانت‌اند قراردادی",
    description:
      "کمک کنید تا تجربیات پخش را برای میلیون‌ها تماشاچی جهانی بهینه کنیم.",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    position: "midlevel",
    tags: ["React", "Performance", "Video"],
    posted: "پیش از ۴ روز",
    salary: "$80k - $120k",
    icon: "📺",
    url: "https://netflix.com/careers",
    type: "contract",
  },
];
